server:
  port: 8080

spring:
  application:
    name: basic-demo

  cache:
    type: redis
    cache-names: products
    multilevel:
      time-to-live: 60s
      cache-null-values: true
      local:
        max-size: 2000
        expiry-jitter: 40
        time-to-live: 30s
      caches:
        products:
          time-to-live: 5m
          local:
            max-size: 500
            time-to-live: 1m
            expiry-jitter: 10
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    io.github.suppie.spring.cache: TRACE
